from playwright.sync_api import Page

from pages.base_page import BackofficePage


class TraderDashboardPage(BackofficePage):
    """Page Object for the post-login landing dashboard (backoffice-ui: src/resources/trader-dashboard).

    Filter chips (Phase / Kickoff window / PIC assignment) are Radix
    ToggleGroup items rendered as role="radio", not role="button" -- verified
    live against admin.uat.cypherlab.tech. Summary cards and filter
    groups are scoped via their stable `data-slot` wrapper (shadcn/ui
    convention in this app, not an autogenerated class) since the visible
    labels ("Turnover", "All", "Status"...) repeat across the page.
    """

    URL_PATH = "/trader-dashboard"
    HEADING_TEXT = "Trader Dashboard"

    def __init__(self, page: Page):
        super().__init__(page)
        self.table = page.get_by_role("table")
        self.search_input = page.get_by_placeholder("Search by Match ID or team...")
        self.phase_filter = page.locator("[data-slot='filter-group-phase']")
        self.kickoff_filter = page.locator("[data-slot='filter-group-kickoff']")
        self.pic_filter = page.locator("[data-slot='filter-group-pic']")
        self.sport_select = page.locator("[data-slot='filter-group-sport']").get_by_role("combobox")
        self.league_select = page.locator("[data-slot='filter-group-league']").get_by_role("combobox")

    def card_text(self, label: str) -> str:
        """Full text of the summary card whose heading is `label` (e.g. "My Matches")."""
        card = self.page.get_by_text(label, exact=True).locator("xpath=ancestor::div[@data-slot='card']").first
        return card.inner_text()

    def filter_by_phase(self, option: str):
        self.phase_filter.get_by_role("radio", name=option, exact=True).click()
        self.page.wait_for_timeout(1000)

    def filter_by_kickoff_window(self, option: str):
        self.kickoff_filter.get_by_role("radio", name=option, exact=True).click()
        self.page.wait_for_timeout(1000)

    def filter_by_pic_assignment(self, option: str):
        self.pic_filter.get_by_role("radio", name=option, exact=True).click()
        self.page.wait_for_timeout(1000)

    def select_sport(self, name: str):
        self.sport_select.click()
        self.page.get_by_role("option", name=name).click()
        self.page.wait_for_timeout(1000)

    def select_league(self, name: str):
        self.league_select.click()
        self.page.get_by_role("option", name=name).click()
        self.page.wait_for_timeout(1000)

    def search(self, term: str):
        self.search_input.fill(term)
        self.page.wait_for_timeout(500)

    def row_count(self) -> int:
        return self.table.locator("tbody tr").count()

    def row_texts(self) -> list[str]:
        return self.table.locator("tbody tr").all_inner_texts()
